###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "name": "Raven",
  "email": "yhwachjhuabak@gmail.com",
  "password": "password"
}

###
###
POST http://localhost:8080/api/v1/auth/activation
Content-Type: application/json

{
  "code": "898183"
}

###

###

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "yhwachjhuabak@gmail.com",
  "password": "password"
}

###